### ISSUE TITLE
Austria To-Do List

### ISSUE THREAD

**Issue by Stiopa866** [Missions-Expanded/Innocent-Eu4-mod#139]
- [ ] Add an extra option for the Swabian event for if you ally all of them
- [ ] Fix Split France peace offer not adding countries to HRE, inheriting countries it shouldn't (nevers in my game for example)
- [ ] Change Rein in Italy decision to mention ways how to rein in the italian countries, add highlighting for countries not yet reined in
- [ ] Consider claims from Cilli->Trent or in general
- [ ] me_noble_rebels_army missing localisation
- [ ] Add temporary diplomatic slot modifier somewhere. (Either temporary, or permanent but conditional)
- [ ] HAB_balkanize_france_desc missing localisation
- [ ] ME_Austria_Events.17 options have the same tooltip + it's confusing (https://discord.com/channels/431065910040854539/932337853776674816/1015827216673800243) - mention what dying means, inheritance evnet
- [ ] ME_Austria_Events.73 can allow you to get university anywhere
- [ ] Several Results can be highlighted by loc
https://discord.com/channels/431065910040854539/932337853776674816/1015821644591288390
https://discord.com/channels/431065910040854539/932337853776674816/1015826009817366609
- [ ] Tell Stiopa why "Foothold at the Alps" requires Austria to be at peace 😄 
- [ ] Also answer this
https://discord.com/channels/431065910040854539/932337853776674816/1015854734416019476
